version: 2.1

executors:
  main-executor:
    docker:
      - image: cimg/node:18.4.0

working_directory: ~/project

jobs:
  build:
    executor: main-executor
    steps:
      - run: ls
      - checkout
      - run: ls
      - run: echo ${CIRCLE_BUILD_URL}
      - run: echo ${CIRCLE_WORKING_DIRECTORY}
      - run: npm i -g eslint eslint-watch
      - run: npm run lint

  test:
    executor: main-executor
    steps:
      - checkout
      - run: npm run test

  analyze:
    executor: main-executor
    steps:
      - checkout
      - run: npm audit


workflows:
  say-hello-workflow:
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
          requires: [test]
