version: 2.1

executors:
  main-executor:
    docker:
      - image: circleci/node:13.8.0

# working_directory: ~/project

jobs:
  build:
    executor: main-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

  test:
    executor: main-executor
    steps:
      - checkout
      - run: npm install
      - run: npm run test

  analyze:
    executor: main-executor
    steps:
      - checkout
      - run: npm audit


workflows:
  say-hello-workflow:
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
          requires: [test]
