version: 2.1

executors:
  cimg-executor:
    docker:
      - image: cimg/base:2022.06

jobs:
  build:
    executor: cimg-executor
    steps:
      - run: npm run lint

  test:
    executor: cimg-executor
    steps:
      - run: npm run test

  analyze:
    executor: cimg-executor
    steps: npm audit


workflows:
  say-hello-workflow:
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
          requires: [test]
